[package]
name = "swc_plugin_zion"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
random-string = "1.1.0"
serde_json = "1"
swc_core = { version = "0.90.*", features = ["ecma_plugin_transform"] }
