[package]
name = "typegen_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1"
typify = "0.0.16"

[dev-dependencies]
insta = { version = "1.38.0", features = ["json"] }
